name: 'backend-deploy-composite-action'
description: 'deploy backend'

defaults:
  run:
    working-directory: ./backend
    shell: bash

inputs:
  FLY_API_TOKEN:
    required: true

runs:
  using: "composite"
  steps:
  
    - name: use GitHub Action for flyctl 
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy to Fly.io
      run: flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ inputs.FLY_API_TOKEN }}
