version: '3.8'
services:
  server:    
    image: my-app-backend-dev
    build: 
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports: 
      - 3939:4000
    container_name: my-app-backend-dev