name: 'frontend-deploy-composite-action'
description: 'deploy frontend'

# defaults:
#   run:
#     working-directory: ./frontend

inputs:
  FLY_API_TOKEN:
    required: true

runs:
  using: "composite"
  steps:

    - name: use GitHub Action for flyctl 
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy to Fly.io
      working-directory: ./frontend
      run: flyctl deploy --remote-only
      shell: bash
      env:
        FLY_API_TOKEN: ${{ inputs.FLY_API_TOKEN }}
