POST http://localhost:4000/grapql
Content-Type: application/json

{
  "query": "mutation login ($username: String!, $password: String!){ login(username: $username, password: $password) {value}}",
  "variables": {  
    "username": "bombom",
    "password": "secretPassword"
  }
}


