name: Backend Deployment

on: 
  workflow_run:
    workflows: ["Built_And_Test"]
    types: [completed]

defaults:
  run:
    working-directory: ./backend

env: 
  PR_IS_MERGED: ${{ github.event.workflow_run.event == 'push'  }}
  
jobs:
  backend_deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && (contains(join(github.event.commits.*.message), '#backdeploy') || contains(join(github.event.commits.*.message), '#fulldeploy')) }}
    runs-on: ubuntu-22.04
    concurrency: backend-deploy-group
    steps:
      - name: Check PR_IS_MERGED value. if true should mean the pull is merged
        run: |
          echo "PR_IS_MERGED=${{ env.PR_IS_MERGED }}"
          echo ${{ github.event.workflow_run.event == 'push' }}
        working-directory: /
   
      - uses: actions/checkout@v4

      - name: use GitHub Action for flyctl 
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_BACKEND }}