name: Backend Deployment

on: 
  workflow_run:
    workflows: ["Built_And_Test"]
    types: [completed]

defaults:
  run:
    working-directory: ./backend

env: 
  PR_IS_MERGED: ${{ github.event.workflow_run.event == 'push'  }}
  
jobs:
  backend_deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    runs-on: ubuntu-22.04
    concurrency: backend-deploy-group
    
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET}}
      PORT: ${{ secrets.PORT }}
      OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_BACKEND }}

    steps:
      - name: Check PR_IS_MERGED value. if true should mean the pull is merged
        run: |
          echo "PR_IS_MERGED=${{ env.PR_IS_MERGED }}"
          echo ${{ github.event.workflow_run.event == 'push' }}
        working-directory: /
   
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: '22'

      - name: install dependencies on backend
        run: |
          npm ci

      - name: use GitHub Action for flyctl 
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only