name: Built_And_Test

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  built_and_test:
    runs-on: ubuntu-22.04
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    env:
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET}}
      PORT_FOR_TEST: ${{ secrets.PORT_FOR_TEST }}
      VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL}}
      VITE_GRAPHQLWSLINK: ${{ secrets.VITE_GRAPHQLWSLINK}}
    steps:
      - uses: actions/checkout@v4     # checkouts the project source code from Git.
      - uses: actions/setup-node@v4   # set up Node.js, with version 22
        with:                         # parameter for the action
          node-version: '22'
           
      - name: install dependencies on backend
        run: |
          cd ./backend
          npm ci
        env: 
          TEST_MONGODB_URI: ${{env.TEST_MONGODB_URI}}
          PORT_FOR_TEST: ${{ env.PORT_FOR_TEST }}
          JWT_SECRET: ${{ env.JWT_SECRET}}

      - name: install dependencies on frontend
        run: |
          cd ./frontend
          npm ci
        env: 
          VITE_BACKEND_URL: ${{env.VITE_BACKEND_URL}}
          VITE_GRAPHQLWSLINK: ${{ env.VITE_GRAPHQLWSLINK }}
     
      - name: check style
        run: |
          cd ./frontend
          npm run lint

      - name: Install Playwright Browsers
        run: |
          cd ./playwright
          npm ci
          npx playwright install --with-deps chromium
      - name: Run Playwright tests on chromium
        run: |
          cd ./playwright
          npx playwright test --project=chromium
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
