name: Built_And_Test

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

concurrency:
  group: ci-${{ github.ref }} # eg. ci-refs/heads/main
  cancel-in-progress: true

jobs:
  built_and_test:
    runs-on: ubuntu-22.04
    concurrency: deploy-group    #  ensure only only a single job or workflow using the same concurrency group will run at a time.
    env:
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET}}
      PORT_FOR_TEST: ${{ secrets.PORT_FOR_TEST }}
      VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL}}
      VITE_GRAPHQLWSLINK: ${{ secrets.VITE_GRAPHQLWSLINK}}
      OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
    steps:
      - uses: actions/checkout@v4     # checkouts the project source code from Git.
      - uses: actions/setup-node@v4   # set up Node.js, with version 22
        with:                         # parameter for the action
          node-version: '22'
           
      - name: install dependencies on backend
        run: |
          cd ./backend
          npm ci
        env: 
          TEST_MONGODB_URI: ${{env.TEST_MONGODB_URI}}
          PORT_FOR_TEST: ${{ env.PORT_FOR_TEST }}
          JWT_SECRET: ${{ env.JWT_SECRET}}
          OMDB_API_KEY: ${{ env.OMDB_API_KEY }}

      - name: install dependencies on frontend
        run: |
          cd ./frontend
          npm ci
        env: 
          VITE_BACKEND_URL: ${{env.VITE_BACKEND_URL}}
          VITE_GRAPHQLWSLINK: ${{ env.VITE_GRAPHQLWSLINK }}
     
      - name: check style
        run: |
          cd ./frontend
          npm run lint

      - name: Install Playwright Browsers
        run: |
          cd ./playwright
          npm ci
          npx playwright install --with-deps chromium
      - name: Run Playwright tests on chromium
        run: |
          cd ./playwright
          npx playwright test --project=chromium
          
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  
      - name: no failed steps
        if: success()
        run: echo "no failed steps"

  deployment:
    needs: [built_and_test]
    if: ${{ needs.built_and_test.result == 'success' && github.event_name == 'push'}}
    runs-on: ubuntu-22.04
    steps: 
      - uses: actions/checkout@v4
      
      - name: frontdeploy in commit -> deploy frontend
        if: ${{ contains(join(github.event.commits.*.message), '#frontdeploy') }}
        uses: ./.github/actions/frontend-composite-action

      - name: backdeploy in commit -> deploy backend
        if: ${{ contains(join(github.event.commits.*.message), '#backdeploy') }}
        uses: ./.github/actions/backend-composite-action

      - name: fulldeploy in commit -> 1.deploy backend
        if: ${{ contains(join(github.event.commits.*.message), '#fulldeploy') }}
        uses: ./.github/actions/backend-composite-action
      - name: fulldeploy in commit -> 2.deploy frontend
        if: ${{ contains(join(github.event.commits.*.message), '#fulldeploy') }}
        uses: ./.github/actions/frontend-composite-action/

  